"""
FedGAN Training Implementation

Implements Algorithm 1: Federated Generative Adversarial Network (FedGAN)
from the paper arXiv:2006.07228v2.

Main training loop with:
- B=5 agents with local Generators and Discriminators
- K=20 synchronization interval
- Non-IID MNIST data partitioning
- Weighted parameter aggregation
"""

import time
import tensorflow as tf
import numpy as np
from typing import List

from data import prepare_federated_data
from models import create_agent_models, discriminator_loss, generator_loss
from utils import (
    generate_and_save_images,
    create_animation_gif,
    plot_losses,
    save_losses_csv,
    aggregate_model_weights,
    synchronize_models,
    save_checkpoint
)


# ============================================================================
# Algorithm 1 Input Parameters
# ============================================================================

# Number of federated agents
NUM_AGENTS = 5  # B in paper

# Synchronization interval (communication rounds)
SYNC_INTERVAL = 20  # K in paper

# Training parameters
EPOCHS = 50  # Training period
BATCH_SIZE = 64
NOISE_DIM = 100  # Latent dimension for generator input

# Learning rates (a(n) and b(n) in paper)
# Using equal time-scale: a(n) = b(n)
LEARNING_RATE_DISC = 1e-4  # Discriminator learning rate
LEARNING_RATE_GEN = 1e-4   # Generator learning rate

# Adam optimizer parameters (from paper)
ADAM_BETA_1 = 0.5  # Important for GAN stability
ADAM_BETA_2 = 0.999

# Random seed for reproducibility
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)

# Fixed noise for visualization consistency
NUM_EXAMPLES_TO_GENERATE = 16
seed_noise = tf.random.normal([NUM_EXAMPLES_TO_GENERATE, NOISE_DIM])


# ============================================================================
# Training Step Functions
# ============================================================================

def train_step_discriminator(
    discriminator: tf.keras.Model,
    generator: tf.keras.Model,
    disc_optimizer: tf.keras.optimizers.Optimizer,
    real_images: tf.Tensor,
    noise: tf.Tensor
) -> tf.Tensor:
    """
    Perform one discriminator training step for a single agent.
    
    Implements Algorithm 1 Step 1:
    Each agent i calculates local stochastic gradient g_tilde_i(theta_n_i, w_n_i)
    from R_i (local dataset) and fake data generated by local generator.
    
    Algorithm 1 Step 2:
    w_n_i = w_(n-1)_i + a(n-1) * g_tilde_i(theta_(n-1)_i, w_(n-1)_i)
    
    Args:
        discriminator: Agent's local discriminator (w parameters)
        generator: Agent's local generator (theta parameters)
        disc_optimizer: Discriminator optimizer
        real_images: Batch of real images from agent's local dataset R_i
        noise: Random noise for generating fake images
    
    Returns:
        Discriminator loss value
    """
    with tf.GradientTape() as disc_tape:
        # Generate fake images from local generator
        generated_images = generator(noise, training=True)
        
        # Get discriminator outputs
        real_output = discriminator(real_images, training=True)
        fake_output = discriminator(generated_images, training=True)
        
        # Compute loss (corresponds to g_tilde_i)
        disc_loss = discriminator_loss(real_output, fake_output)
    
    # Compute gradients
    gradients_of_discriminator = disc_tape.gradient(
        disc_loss, discriminator.trainable_variables
    )
    
    # Apply gradients: w_n_i = w_(n-1)_i + a(n-1) * g_tilde_i
    disc_optimizer.apply_gradients(
        zip(gradients_of_discriminator, discriminator.trainable_variables)
    )
    
    return disc_loss


def train_step_generator(
    discriminator: tf.keras.Model,
    generator: tf.keras.Model,
    gen_optimizer: tf.keras.optimizers.Optimizer,
    noise: tf.Tensor
) -> tf.Tensor:
    """
    Perform one generator training step for a single agent.
    
    Implements Algorithm 1 Step 1:
    Each agent i calculates local stochastic gradient h_tilde_i(theta_n_i, w_n_i)
    from R_i and fake data generated by the local generator.
    
    Algorithm 1 Step 2:
    theta_n_i = theta_(n-1)_i + b(n-1) * h_tilde_i(theta_(n-1)_i, w_(n-1)_i)
    
    Args:
        discriminator: Agent's local discriminator (w parameters)
        generator: Agent's local generator (theta parameters)
        gen_optimizer: Generator optimizer
        noise: Random noise for generating fake images
    
    Returns:
        Generator loss value
    """
    with tf.GradientTape() as gen_tape:
        # Generate fake images
        generated_images = generator(noise, training=True)
        
        # Get discriminator's opinion on fake images
        fake_output = discriminator(generated_images, training=True)
        
        # Compute loss (corresponds to h_tilde_i)
        gen_loss = generator_loss(fake_output)
    
    # Compute gradients
    gradients_of_generator = gen_tape.gradient(
        gen_loss, generator.trainable_variables
    )
    
    # Apply gradients: theta_n_i = theta_(n-1)_i + b(n-1) * h_tilde_i
    gen_optimizer.apply_gradients(
        zip(gradients_of_generator, generator.trainable_variables)
    )
    
    return gen_loss


def synchronize_agents(
    generators: List[tf.keras.Model],
    discriminators: List[tf.keras.Model],
    agent_weights: np.ndarray
) -> None:
    """
    Synchronize all agents by averaging their model parameters.
    
    Implements Algorithm 1 Step 3 (if n mod K = 0):
    1. All agents send parameters to intermediary
    2. Intermediary calculates weighted averages:
       w_n = sum_j (p_j * w_n_j)
       theta_n = sum_j (p_j * theta_n_j)
    3. Intermediary sends back w_n, theta_n to all agents
    4. Agents update: w_n_i = w_n, theta_n_i = theta_n
    
    Args:
        generators: List of all agent generators
        discriminators: List of all agent discriminators
        agent_weights: Aggregation weights p_i (based on dataset sizes)
    """
    # Aggregate generator parameters (theta)
    aggregated_gen_weights = aggregate_model_weights(generators, agent_weights)
    
    # Aggregate discriminator parameters (w)
    aggregated_disc_weights = aggregate_model_weights(discriminators, agent_weights)
    
    # Broadcast aggregated parameters to all agents
    synchronize_models(generators, aggregated_gen_weights)
    synchronize_models(discriminators, aggregated_disc_weights)


def train_fedgan(
    epochs: int = EPOCHS,
    batch_size: int = BATCH_SIZE,
    num_agents: int = NUM_AGENTS,
    sync_interval: int = SYNC_INTERVAL
) -> None:
    """
    Main FedGAN training loop implementing Algorithm 1.
    
    Training Loop (for n=1,2,...,N-1):
    1. Local Gradient Computation (parallel across agents)
    2. Local Parameter Update (parallel across agents)
    3. Synchronization (if n mod K = 0)
    
    Args:
        epochs: Number of training epochs
        batch_size: Batch size for training
        num_agents: Number of federated agents (B)
        sync_interval: Synchronization interval (K)
    """
    print("=" * 80)
    print("FedGAN Training - Algorithm 1 Implementation")
    print("=" * 80)
    print(f"Agents (B): {num_agents}")
    print(f"Synchronization Interval (K): {sync_interval}")
    print(f"Epochs: {epochs}")
    print(f"Batch Size: {batch_size}")
    print(f"Learning Rate (Discriminator): {LEARNING_RATE_DISC}")
    print(f"Learning Rate (Generator): {LEARNING_RATE_GEN}")
    print("=" * 80)
    
    # ========================================================================
    # Algorithm 1 Input: Prepare datasets R_i for each agent
    # ========================================================================
    print("\nPreparing federated datasets...")
    agent_datasets, agent_weights = prepare_federated_data(batch_size, num_agents)
    
    # ========================================================================
    # Algorithm 1 Input: Initialize local models
    # w_i_0 = w_hat and theta_i_0 = theta_hat for all i
    # ========================================================================
    print("\nInitializing agent models...")
    generators, discriminators = create_agent_models(num_agents, NOISE_DIM)
    
    # Create optimizers for each agent
    # a(n) = discriminator learning rate, b(n) = generator learning rate
    gen_optimizers = [
        tf.keras.optimizers.Adam(LEARNING_RATE_GEN, beta_1=ADAM_BETA_1, beta_2=ADAM_BETA_2)
        for _ in range(num_agents)
    ]
    disc_optimizers = [
        tf.keras.optimizers.Adam(LEARNING_RATE_DISC, beta_1=ADAM_BETA_1, beta_2=ADAM_BETA_2)
        for _ in range(num_agents)
    ]
    
    print(f"Created {num_agents} generator-discriminator pairs")
    
    # ========================================================================
    # Training Loop: for n=1,2,...,N-1
    # ========================================================================
    losses_history = []
    global_step = 0
    
    print("\nStarting training...")
    print("=" * 80)
    
    for epoch in range(epochs):
        start_time = time.time()
        
        epoch_gen_losses = []
        epoch_disc_losses = []
        
        # Convert datasets to iterators
        agent_iterators = [iter(ds) for ds in agent_datasets]
        
        # Determine number of batches per epoch (based on smallest dataset)
        steps_per_epoch = min([
            tf.data.experimental.cardinality(ds).numpy() 
            for ds in agent_datasets
        ])
        
        for step in range(steps_per_epoch):
            step_gen_losses = []
            step_disc_losses = []
            
            # ================================================================
            # Algorithm 1 Step 1 & 2: Local Training (parallel across agents)
            # ================================================================
            for agent_id in range(num_agents):
                # Get batch from agent's local dataset R_i
                try:
                    images, _ = next(agent_iterators[agent_id])
                except StopIteration:
                    agent_iterators[agent_id] = iter(agent_datasets[agent_id])
                    images, _ = next(agent_iterators[agent_id])
                
                # Generate random noise
                noise = tf.random.normal([images.shape[0], NOISE_DIM])
                
                # Train discriminator (Step 1 & 2 for w parameters)
                disc_loss = train_step_discriminator(
                    discriminators[agent_id],
                    generators[agent_id],
                    disc_optimizers[agent_id],
                    images,
                    noise
                )
                
                # Train generator (Step 1 & 2 for theta parameters)
                gen_loss = train_step_generator(
                    discriminators[agent_id],
                    generators[agent_id],
                    gen_optimizers[agent_id],
                    noise
                )
                
                step_gen_losses.append(gen_loss.numpy())
                step_disc_losses.append(disc_loss.numpy())
            
            epoch_gen_losses.extend(step_gen_losses)
            epoch_disc_losses.extend(step_disc_losses)
            
            global_step += 1
            
            # ================================================================
            # Algorithm 1 Step 3: Synchronization (if n mod K = 0)
            # ================================================================
            if global_step % sync_interval == 0:
                synchronize_agents(generators, discriminators, agent_weights)
                print(f"  [Step {global_step}] Synchronized all agents")
        
        # Compute average losses for the epoch
        avg_gen_loss = np.mean(epoch_gen_losses)
        avg_disc_loss = np.mean(epoch_disc_losses)
        
        losses_history.append((epoch + 1, avg_gen_loss, avg_disc_loss))
        
        # Generate and save images every epoch
        generate_and_save_images(
            generators[0],  # Use first agent's generator (all synchronized)
            epoch + 1,
            seed_noise
        )
        
        # Save checkpoint at synchronization points
        if (epoch + 1) % 10 == 0:
            save_checkpoint(
                generators, discriminators,
                gen_optimizers, disc_optimizers,
                epoch + 1
            )
        
        epoch_time = time.time() - start_time
        
        print(f"Epoch {epoch + 1}/{epochs} - "
              f"Time: {epoch_time:.2f}s - "
              f"Gen Loss: {avg_gen_loss:.4f} - "
              f"Disc Loss: {avg_disc_loss:.4f}")
    
    # ========================================================================
    # Post-training: Save results
    # ========================================================================
    print("\n" + "=" * 80)
    print("Training complete! Generating final outputs...")
    
    # Create animation GIF
    create_animation_gif()
    
    # Plot and save losses
    plot_losses(losses_history)
    save_losses_csv(losses_history)
    
    # Final checkpoint
    save_checkpoint(
        generators, discriminators,
        gen_optimizers, disc_optimizers,
        epochs
    )
    
    print("=" * 80)
    print("FedGAN training finished successfully!")
    print("Results saved to outputs/")
    print("=" * 80)


if __name__ == "__main__":
    # Run FedGAN training
    train_fedgan()
